on:
  push:
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    name: Generate Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation
        with:
          args: /home/runner/work/Sabuto.Trello/Sabuto.Trello/DockFx/docfx.json