on:
  push:
jobs:
  generate-docs:
    runs-on: windows-latest
    name: Generate Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1.6.0
        with:
          args: install docfx
      - name: Install dependencies
        run: dotnet restore src/Sabuto.Trello/Sabuto.Trello.Core/Sabuto.Trello.Core.csproj
      - name: DocFX Build
        working-directory: DocFx
        run: docfx docfx.json
        continue-on-error: false
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
