on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-and-publish-nuget:
    runs-on: ubuntu-latest
    name: Generate Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Setup .NET Core 6.0.*
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: Build
        run: dotnet build src/Sabuto.Trello/Sabuto.Trello.Core/Sabuto.Trello.Core.csproj -p:Version=${VERSION} --configuration Release
      - name: Pack
        run: | 
          dotnet pack src/Sabuto.Trello/Sabuto.Trello.Core/Sabuto.Trello.Core.csproj --configuration Release /p:Version=${VERSION}
      - name: Publish
        run: |
          ls src/Sabuto.Trello/Sabuto.Trello.Core/bin/Release
          dotnet nuget push src/Sabuto.Trello/Sabuto.Trello.Core/bin/Release/Sabuto.Trello.Core.${VERSION}.nupkg --api-key oy2isp4icon7p7jsfezqma7yah7ye2aerjeeiaqsbikpi4 -s 'https://api.nuget.org/v3/index.json'